// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using ThisRoofN.iOS.ValueConverters;
using MvvmCross.Binding.iOS.Views;
using MvvmCross.Binding.BindingContext;

namespace ThisRoofN.iOS
{
	public partial class HomeStructureItemCell : MvxTableViewCell
	{
		public static string Identifier = "HomeStructureItemCell";
		public HomeStructureItemCell (IntPtr handle) : base (handle)
		{
			this.DelayBind (() => {
				var set = this.CreateBindingSet<HomeStructureItemCell, CheckboxItemModel>();
				set.Bind(iv_checkbox).To(vm => vm.Selected).WithConversion(new CheckmarkConverter());
				set.Bind(lbl_title).To(vm => vm.Title);
				set.Apply();
			});
		}
	}
}
