// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using MvvmCross.Binding.iOS.Views;
using MvvmCross.Binding.BindingContext;
using ThisRoofN.Models.App;

namespace ThisRoofN.iOS
{
	public partial class LocationSuggestionCell : MvxTableViewCell
	{
		public static string Identifier = "LocationSuggestionCell";
		public LocationSuggestionCell (IntPtr handle) : base (handle)
		{
			this.DelayBind (() => {
				var set = this.CreateBindingSet<LocationSuggestionCell, TRGoogleMapPlace>();
				set.Bind(lbl_address).To(vm => vm.FullAddress);
				set.Apply();
			});
		}
	}
}
