// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using MvvmCross.Binding.iOS.Views;
using MvvmCross.Binding.BindingContext;
using ThisRoofN.iOS.ValueConverters;

namespace ThisRoofN.iOS
{
	public partial class SearchAreaCommuteCell : MvxTableViewCell
	{
		public static string Identifier = "SearchAreaCommuteCell";
		public SearchAreaCommuteCell (IntPtr handle) : base (handle)
		{
			this.DelayBind (() => {
				var set = this.CreateBindingSet<SearchAreaCommuteCell, CheckboxItemModel>();
				set.Bind(swt_option).To(vm => vm.Selected);
				set.Bind(lbl_title).To(vm => vm.Title);
				set.Apply();
			});
		}
	}
}
