// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using MvvmCross.Binding.iOS.Views;
using MvvmCross.Binding.BindingContext;
using ThisRoofN.Models.App;

namespace ThisRoofN.iOS
{
	public partial class SearchResultListViewCell : MvxTableViewCell
	{
		public static string Identifier = "SearchResultListViewCell";

		public SearchResultListViewCell (IntPtr handle) : base (handle)
		{
			this.DelayBind (() => {
				var set = this.CreateBindingSet<SearchResultListViewCell, TRCottageSimple>();
				set.Bind(lbl_title).To(vm => vm.Title);
				set.Bind(lbl_price).To(vm => vm.Price);
				set.Bind(img_property).For(i => i.ImageUrl).To(vm => vm.PrimaryPhotoLink);
				set.Apply();
			});
		}

		public MvxImageView IVItem {
			get {
				return img_property;
			}
		}
	}
}
