// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using ThisRoofN.ViewModels;
using MvvmCross.Binding.iOS.Views;
using CoreGraphics;
using ThisRoofN.iOS.Helpers;
using MvvmCross.Binding.BindingContext;

namespace ThisRoofN.iOS
{
	public partial class SearchResultListView : BaseViewController
	{
		public SearchResultListView (IntPtr handle) : base (handle)
		{	
		}

		public SearchResultListViewModel ViewModelInstance 
		{
			get {
				return (SearchResultListViewModel)base.ViewModel;
			}
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			// Bind Locatin Suggesion Table
			var listSource = new SearchResultListTableViewSource (this, tbl_list);
			tbl_list.Source = listSource;
			tbl_list.RowHeight = UITableView.AutomaticDimension;
			tbl_list.TableFooterView = new UITableView (CGRect.Empty);
			tbl_list.ReloadData ();

			tbl_list.SeparatorStyle = UITableViewCellSeparatorStyle.None;

			var bindingSet = this.CreateBindingSet<SearchResultListView, SearchResultListViewModel> ();
			bindingSet.Bind (listSource).To (vm => vm.ListItems);
			bindingSet.Bind (loadingView).For(i => i.Hidden).To (vm => vm.IsHideLoading);
			bindingSet.Bind (loadingLabel).To (vm => vm.LoadingText);
			bindingSet.Apply ();
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);
		}

		public class SearchResultListTableViewSource : MvxTableViewSource
		{
			SearchResultListView masterView;

			public SearchResultListTableViewSource (SearchResultListView _masterview, UITableView tv) : base (tv)
			{
				masterView = _masterview;
			}

			public override nfloat GetHeightForRow (UITableView tableView, NSIndexPath indexPath)
			{
				return 90.0f;
			}

			protected override UITableViewCell GetOrCreateCellFor (UITableView tableView, NSIndexPath indexPath, object item)
			{
				SearchResultListViewCell cell = (SearchResultListViewCell)tableView.DequeueReusableCell (SearchResultListViewCell.Identifier);

				cell.IVItem.ContentMode = UIViewContentMode.ScaleAspectFill;
				cell.IVItem.DefaultImagePath = NSBundle.MainBundle.PathForResource ("img_placeholder_small", "png");
				return cell;
			}

			public override void RowSelected (UITableView tableView, NSIndexPath indexPath)
			{
				tableView.DeselectRow (indexPath, true);
				masterView.ViewModelInstance.DetailCommand.Execute (indexPath.Row);
			}
		}
	}
}
