// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ThisRoofN.iOS
{
	public partial class CheckboxCVCell : UICollectionViewCell
	{
		public CheckboxCVCell (IntPtr handle) : base (handle)
		{
		}
	}
}
