// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ThisRoofN.iOS
{
	public partial class SearchBedsCell : UITableViewCell, ISearchCell
	{
		public static string Identifier = "SearchBedsCell";
		private nfloat cellHeight;

		public SearchBedsCell (IntPtr handle) : base (handle)
		{
		}

		public nfloat CellHeight 
		{
			get
			{
				return cellHeight;
			}
		}

		public void HandleExpandTap()
		{
		}
	}
}
