// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using ThisRoofN.iOS.Helpers;
using RangeSlider;

namespace ThisRoofN.iOS
{
	public partial class SearchBudgetCell : UITableViewCell, ISearchCell
	{
		public static string Identifier = "SearchBudgetCell";
		private nfloat cellHeight;
		private NormalSearchViewController masterView;
		private RangeSliderView rangeSlider;

		public SearchBudgetCell (IntPtr handle) : base (handle)
		{
		}

		public nfloat CellHeight 
		{
			get
			{
				return cellHeight;
			}
		}

		public void BindData(NormalSearchViewController _masterView)
		{
			this.masterView = _masterView;

			masterView.BindingSet.Bind (lbl_budget).To (vm => vm.BudgetString);

			InitUI ();
		}

		public void HandleExpandTap()
		{
		}

		public void InitUI()
		{
			rangeSlider = new RangeSliderView (new CoreGraphics.CGRect (16, img_valueMark.Frame.Bottom + 8, UIScreen.MainScreen.Bounds.Width - 32, 40));

			rangeSlider.MinValue = TRConstant.MinValidBudget;
			rangeSlider.MaxValue = TRConstant.MaxValidBudget;

			if (masterView.ViewModelInstance.MinBudget < TRConstant.MinValidBudget || masterView.ViewModelInstance.MinBudget > TRConstant.MaxValidBudget) {
				rangeSlider.LeftValue = TRConstant.MinValidBudget;
			} else {
				rangeSlider.LeftValue = (nfloat)masterView.ViewModelInstance.MinBudget;
			}

			if (masterView.ViewModelInstance.MaxBudget > TRConstant.MaxValidBudget || masterView.ViewModelInstance.MaxBudget < TRConstant.MinValidBudget) {
				rangeSlider.RightValue = TRConstant.MaxValidBudget;
			} else {
				rangeSlider.RightValue = (nfloat)masterView.ViewModelInstance.MaxBudget;
			}
				
			rangeSlider.LeftValueChanged += (nfloat value) => {
				masterView.ViewModelInstance.MinBudget = rangeSlider.LeftValue;
			};

			rangeSlider.RightValueChanged += (nfloat value) => {
				masterView.ViewModelInstance.MaxBudget = rangeSlider.RightValue;
			};

			this.AddSubview (rangeSlider);

			cellHeight = rangeSlider.Frame.Bottom + 16;
		}
	}
}
