// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ThisRoofN.iOS
{
	public partial class SearchButtonCell : UITableViewCell, ISearchCell
	{
		public static string Identifier = "SearchButtonCell";
		private nfloat cellHeight;
		private NormalSearchViewController masterView;

		public SearchButtonCell (IntPtr handle) : base (handle)
		{
		}

		public nfloat CellHeight 
		{
			get
			{
				return cellHeight;
			}
		}

		public void BindData(NormalSearchViewController _masterView)
		{
			this.masterView = _masterView;

			cellHeight = btn_saveSearch.Frame.Bottom;
		}

		public void HandleExpandTap()
		{
		}
	}
}
