// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ThisRoofN.iOS
{
	public partial class SearchSoryByCell : UITableViewCell, ISearchCell
	{
		public static string Identifier = "SearchSoryByCell";
		private nfloat cellHeight;
		private NormalSearchViewController masterView;

		public SearchSoryByCell (IntPtr handle) : base (handle)
		{
		}

		public nfloat CellHeight 
		{
			get
			{
				return cellHeight;
			}
		}

		public void BindData(NormalSearchViewController _masterView)
		{
			this.masterView = _masterView;

			UIComboBox soryByComboBox = new UIComboBox (masterView.ViewModelInstance.SortTypes, 0, txt_sortBy, 
				                            (indexe, text) => {
					masterView.ViewModelInstance.SelectedSortType = text;
				});

			InitUI ();
		}

		public void HandleExpandTap()
		{
		}

		public void InitUI()
		{
			cellHeight = txt_sortBy.Frame.Bottom + 8;
		}
	}
}
