// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ThisRoofN.iOS
{
	public partial class SearchDetailFilterCell : UITableViewCell
	{
		public static string Identifier = "SearchDetailFilterCell";
		private nfloat cellHeight;
		private NormalSearchViewController masterView;

		public SearchDetailFilterCell (IntPtr handle) : base (handle)
		{
		}

		public nfloat CellHeight 
		{
			get
			{
				return cellHeight;
			}
		}

		public void BindData(NormalSearchViewController _masterView)
		{
			this.masterView = _masterView;

//			masterView.BindingSet.Bind (lbl_budget).To (vm => vm.BudgetString);

			InitUI ();
		}

		public void HandleExpandTap()
		{
		}

		public void InitUI()
		{
			cellHeight = view_filter4.Frame.Bottom + 16;
		}
	}
}
