// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ThisRoofN.iOS
{
	public partial class SearchBedsCell : UITableViewCell, ISearchCell
	{
		public static string Identifier = "SearchBedsCell";
		private NormalSearchViewController masterView;
		private nfloat cellHeight;
		private bool expanded;

		public SearchBedsCell (IntPtr handle) : base (handle)
		{
		}

		public nfloat CellHeight 
		{
			get
			{
				return cellHeight;
			}
		}

		public void BindData(NormalSearchViewController _masterView)
		{
			this.masterView = _masterView;

			InitUI ();
		}

		public void HandleExpandTap()
		{
			expanded = !expanded;

			masterView.MasterTableView.BeginUpdates ();
			if (expanded) {
				img_expandMarker.Image = UIImage.FromBundle ("icon_arrow_blue_down");
				cellHeight = seg_bedCount.Frame.Bottom + 8;
			} else {
				img_expandMarker.Image = UIImage.FromBundle ("icon_arrow_blue_right");
				cellHeight = view_cellTitle.Frame.Bottom;
			}
			masterView.MasterTableView.EndUpdates ();
		}

		private void InitUI()
		{
			cellHeight = view_cellTitle.Frame.Bottom;
			UITapGestureRecognizer expandTap = new UITapGestureRecognizer (HandleExpandTap);
			view_cellTitle.UserInteractionEnabled = true;
			view_cellTitle.RemoveGestureRecognizer (expandTap);
			view_cellTitle.AddGestureRecognizer (expandTap);

			seg_bedCount.ValueChanged += (object sender, EventArgs e) => {
				masterView.ViewModelInstance.MinBeds = (int)seg_bedCount.SelectedSegment;
			};
		}
	}
}
