// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ThisRoofN.iOS
{
	public partial class SearchAreaCell : UITableViewCell, ISearchCell
	{
		public static string Identifier = "SearchAreaCell";
		private nfloat cellHeight;


		public SearchAreaCell (IntPtr handle) : base (handle)
		{
		}

		public nfloat CellHeight 
		{
			get
			{
				return cellHeight;
			}
		}

		public void HandleExpandTap()
		{
		}

//		public void BindData(NormalSearchViewController masterView, DiscountsA
	}
}
