// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using MvvmCross.Binding.iOS.Views;
using MvvmCross.Binding.BindingContext;
using ThisRoofN.iOS.ValueConverters;

namespace ThisRoofN.iOS
{
	public partial class SearchAreaCheckboxCVCell : MvxCollectionViewCell
	{
		public SearchAreaCheckboxCVCell (IntPtr handle) : base (handle)
		{
			this.DelayBind (() => {
				var set = this.CreateBindingSet<SearchAreaCheckboxCVCell, CheckboxItemModel>();
				set.Bind(iv_check).To(vm => vm.Selected).WithConversion(new CheckmarkConverter());
				set.Bind(lbl_title).To(vm => vm.Title);
				set.Apply();
			});
		}
	}
}
