// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using MvvmCross.Binding.iOS.Views;
using MvvmCross.Binding.BindingContext;
using ThisRoofN.Models.Service;
using ThisRoofN.Database.Entities;

namespace ThisRoofN.iOS
{
	public partial class SavedPropertyCell : MvxTableViewCell
	{
		public static string Identifier = "SavedPropertyCell";
		public SavedPropertyCell (IntPtr handle) : base (handle)
		{
			this.DelayBind (() => {
				var set = this.CreateBindingSet<SavedPropertyCell, TREntityLikes>();
				set.Bind(lbl_price).To(vm => vm.FormattedSalePrice);
				set.Bind(lbl_address).To(vm => vm.Address);
				set.Bind(lbl_cityStateZip).To(vm => vm.CityStateZip);
				set.Bind(img_primary).For(i => i.ImageUrl).To(vm => vm.PrimaryPhotoURL);
				set.Apply();
			});
		}

		public MvxImageView IVItem {
			get {
				return img_primary;
			}
		}
	}
}
