// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using MvvmCross.Binding.iOS.Views;
using CoreGraphics;
using MvvmCross.Binding.BindingContext;
using ThisRoofN.ViewModels;
using ThisRoofN.iOS.Helpers;

namespace ThisRoofN.iOS
{
	public partial class SavedPropertiesView : BaseViewController
	{
		public SavedPropertiesView (IntPtr handle) : base (handle)
		{	
		}

		public SavedPropertiesViewModel ViewModelInstance 
		{
			get {
				return (SavedPropertiesViewModel)base.ViewModel;
			}
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			SetupNavigationBar (false);

			// Bind Locatin Suggesion Table
			var savedDataSource = new SavedPropertiesTableViewSource (this, tbl_saved);
			tbl_saved.Source = savedDataSource;
			tbl_saved.RowHeight = UITableView.AutomaticDimension;
			tbl_saved.TableFooterView = new UITableView (CGRect.Empty);
			tbl_saved.ReloadData ();

			tbl_saved.SeparatorColor = TRColorHelper.LightBlue;

			var bindingSet = this.CreateBindingSet<SavedPropertiesView, SavedPropertiesViewModel> ();
			bindingSet.Bind (backButton).To (vm => vm.CloseCommand);
			bindingSet.Bind (savedDataSource).To (vm => vm.SavedProperties);
			bindingSet.Apply ();
		}

		public class SavedPropertiesTableViewSource : MvxTableViewSource
		{
			SavedPropertiesView masterView;

			public SavedPropertiesTableViewSource (SavedPropertiesView _masterview, UITableView tv) : base (tv)
			{
				masterView = _masterview;
			}

			public override nfloat GetHeightForRow (UITableView tableView, NSIndexPath indexPath)
			{
				return 90.0f;
			}

			protected override UITableViewCell GetOrCreateCellFor (UITableView tableView, NSIndexPath indexPath, object item)
			{
				SavedPropertyCell cell = (SavedPropertyCell)tableView.DequeueReusableCell (SavedPropertyCell.Identifier);
				cell.IVItem.ContentMode = UIViewContentMode.ScaleAspectFill;
				cell.IVItem.DefaultImagePath = NSBundle.MainBundle.PathForResource ("img_placeholder_small", "png");
				return cell;
			}

			public override void RowSelected (UITableView tableView, NSIndexPath indexPath)
			{
				tableView.DeselectRow (indexPath, true);
				masterView.ViewModelInstance.DetailCommand.Execute (indexPath.Row);
			}
		}
	}
}
