// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using MvvmCross.Binding.BindingContext;
using ThisRoofN.ViewModels;

namespace ThisRoofN.iOS
{
	public partial class SettingsView : BaseViewController
	{
		public SettingsView (IntPtr handle) : base (handle)
		{
		}

		public SettingsViewModel ViewModelInstance
		{
			get {
				return (SettingsViewModel)this.ViewModel;
			}
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			SetupNavigationBar (false);

			var set = this.CreateBindingSet<SettingsView, SettingsViewModel> ();
			set.Bind (backButton).To (vm => vm.CloseCommand);
			set.Bind (btn_savedProperty).To (vm => vm.SavedPropertyCommand);
			set.Bind (btn_support).To (vm => vm.SupportCommand);
			set.Bind (btn_privacyPolicy).To (vm => vm.PrivacyCommand);
			set.Bind (btn_termsOfUse).To (vm => vm.TermsCommand);
			set.Bind (btn_licenses).To (vm => vm.LicenseCommand);
			set.Bind (btn_cliearLiked).To (vm => vm.ClearLikeCommand);
			set.Bind (btn_clearDisliked).To (vm => vm.ClearDislikeCommand);
			set.Bind (btn_enableAllTutorial).To (vm => vm.EnableAllTutorialCommand);
			set.Bind (btn_logout).To (vm => vm.LogoutCommand);
			set.Apply ();
		}
	}
}
