// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using ThisRoofN.ViewModels;
using Acr.UserDialogs;
using MvvmCross.Binding.BindingContext;

namespace ThisRoofN.iOS
{
	public partial class TRWebViewController : BaseViewController
	{
		public TRWebViewController (IntPtr handle) : base (handle)
		{
		}

		public TRWebViewModel ViewModelInstance
		{
			get {
				return (TRWebViewModel)this.ViewModel;
			}
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			SetupNavigationBar (false);

			var set = this.CreateBindingSet<TRWebViewController, TRWebViewModel> ();
			set.Bind (backButton).To (vm => vm.CloseCommand);
			set.Bind (loadingView).For(i => i.Hidden).To (vm => vm.IsHideLoading);
			set.Bind (loadingLabel).To (vm => vm.LoadingText);
			set.Apply ();
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);

			ViewModelInstance.IsLoading = true;
			ViewModelInstance.LoadingText = "Loading";
			view_web.LoadRequest (new NSUrlRequest(new NSUrl(ViewModelInstance.ContentLink)));
			view_web.ScalesPageToFit = true;

			view_web.LoadFinished += (object sender, EventArgs e) => {
				ViewModelInstance.IsLoading = false;
			};
		}
	}
}
