// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ThisRoofN.iOS
{
	public partial class SearchCVCell : UICollectionViewCell
	{
		public SearchCVCell (IntPtr handle) : base (handle)
		{
		}

		public void InitCell(ThisRoofN.ViewModels.SearchViewModel.ModalType item)
		{
			switch (item) {
			case ThisRoofN.ViewModels.SearchViewModel.ModalType.SearchArea:
				
				iv_item.Image = UIImage.FromBundle ("img_search_location");
				lbl_title.Text = "LOCATION";
				break;
			case ThisRoofN.ViewModels.SearchViewModel.ModalType.Lifestyle:
				lbl_title.Text = "LIFESTYLE";
				iv_item.Image = UIImage.FromBundle ("img_search_lifeStyle");
				break;
			case ThisRoofN.ViewModels.SearchViewModel.ModalType.InArea:
				lbl_title.Text = "IN THE AREA";
				iv_item.Image = UIImage.FromBundle ("img_search_inArea");
				break;
			case ThisRoofN.ViewModels.SearchViewModel.ModalType.HomeDetails:
				lbl_title.Text = "HOME DETAILS";
				iv_item.Image = UIImage.FromBundle ("img_search_homeDetails");
				break;
			case ThisRoofN.ViewModels.SearchViewModel.ModalType.InHome:
				lbl_title.Text = "IN THE HOME";
				iv_item.Image = UIImage.FromBundle ("img_search_inHome");
				break;
			case ThisRoofN.ViewModels.SearchViewModel.ModalType.SavedHome:
				lbl_title.Text = "SAVED HOME";
				iv_item.Image = UIImage.FromBundle ("img_savedHomes");
				break;
			}
		}
	}
}
