// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using MvvmCross.Binding.BindingContext;
using ThisRoofN.ViewModels;
using ThisRoofN.iOS.Helpers;

namespace ThisRoofN.iOS
{
	public partial class AffordSearchView : BaseViewController
	{
		public AffordSearchView (IntPtr handle) : base (handle)
		{
		}

		public AffordSearchViewModel ViewModelInstance
		{
			get {
				return (AffordSearchViewModel)this.ViewModel;
			}
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			SetupNavigationBar ();

			this.View.AddGestureRecognizer (new UITapGestureRecognizer (() => {
				this.View.EndEditing(true);
			}));

			var bindingSet = this.CreateBindingSet<AffordSearchView, AffordSearchViewModel> ();
			bindingSet.Bind (backButton).To (vm => vm.CloseCommand);
			bindingSet.Bind (settingButton).To (vm => vm.SettingCommand);
			bindingSet.Bind (txt_annualIncome).To (vm => vm.AnnualIncome);
			bindingSet.Bind (txt_monthlyDebts).To (vm => vm.MonthlyDebts);
			bindingSet.Bind (txt_downPayment).To (vm => vm.DownPayment);
			bindingSet.Bind (txt_propertyTax).To (vm => vm.PropertyTax);
			bindingSet.Bind (txt_insurance).To (vm => vm.PropertyInsurance);
			bindingSet.Bind (txt_hoaDues).To (vm => vm.HoaDues);
			bindingSet.Bind (btn_calc).To (vm => vm.CalcCommand);
			bindingSet.Apply ();

			view_annualIncome.Layer.BorderColor = TRColorHelper.ThemeBlue.CGColor;
			view_monthlyDebts.Layer.BorderColor = TRColorHelper.ThemeBlue.CGColor;
			view_downPayment.Layer.BorderColor = TRColorHelper.ThemeBlue.CGColor;

			view_propertyTax.Layer.BorderColor = TRColorHelper.ThemeBlue.CGColor;
			view_insurance.Layer.BorderColor = TRColorHelper.ThemeBlue.CGColor;
			view_hoaDues.Layer.BorderColor = TRColorHelper.ThemeBlue.CGColor;

			view_annualIncome.Layer.BorderWidth = 1.0f;
			view_monthlyDebts.Layer.BorderWidth = 1.0f;
			view_downPayment.Layer.BorderWidth = 1.0f;
			view_propertyTax.Layer.BorderWidth = 1.0f;
			view_insurance.Layer.BorderWidth = 1.0f;
			view_hoaDues.Layer.BorderWidth = 1.0f;

			view_annualIncome.Layer.CornerRadius = 3.0f;
			view_monthlyDebts.Layer.CornerRadius = 3.0f;
			view_downPayment.Layer.CornerRadius = 3.0f;
			view_propertyTax.Layer.CornerRadius = 3.0f;
			view_insurance.Layer.CornerRadius = 3.0f;
			view_hoaDues.Layer.CornerRadius = 3.0f;

			seg_loanTerm.SelectedSegment = ViewModelInstance.LoanTerm;
			seg_loanTerm.ValueChanged += (object sender, EventArgs e) => {
				ViewModelInstance.LoanTerm = (int)seg_loanTerm.SelectedSegment;
			};

			img_taxCheck.UserInteractionEnabled = true;
			img_taxCheck.Image = UIImage.FromBundle("icon_checkbox_emp");
			img_taxCheck.AddGestureRecognizer (new UITapGestureRecognizer (() => {
				if(ViewModelInstance.IncludeTax) {
					img_taxCheck.Image = UIImage.FromBundle("icon_checkbox_emp");
				} else {
					img_taxCheck.Image = UIImage.FromBundle("icon_checkbox_tick");
				}

				ViewModelInstance.IncludeTax = !ViewModelInstance.IncludeTax;
			}));
		}
	}
}
