// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using RangeSlider;
using ThisRoofN.ViewModels;
using CoreGraphics;
using MvvmCross.Binding.BindingContext;

namespace ThisRoofN.iOS
{
	public partial class SearchView : BaseViewController
	{
		private RangeSliderView priceRangeSlider;
		public SearchView (IntPtr handle) : base (handle)
		{
		}

		public SearchViewModel ViewModelInstance {
			get {
				return (SearchViewModel)base.ViewModel;
			}
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			SetupNavigationBar ();

			InitRangeSlider ();

			var bindingSet = this.CreateBindingSet<SearchView, SearchViewModel> ();
			bindingSet.Bind (lbl_priceRange).To (vm => vm.BudgetString);
			bindingSet.Bind (backButton).To (vm => vm.CloseCommand);
			bindingSet.Bind (settingButton).To (vm => vm.SettingCommand);
			bindingSet.Bind (btn_searchArea).To (vm => vm.GotoSearchAreaCommand);
			bindingSet.Apply ();

			UIComboBox soryByComboBox = new UIComboBox (ViewModelInstance.SortTypes, 0, txt_sortBy, 
				(index, text) => {
					ViewModelInstance.SelectedSortType = text;
				});
		}

		private void InitRangeSlider() {
			priceRangeSlider = new RangeSliderView (new CGRect (0, 0, this.view_rangeSlider.Frame.Width, this.view_rangeSlider.Frame.Height));

			priceRangeSlider.MinValue = TRConstant.MinValidBudget;
			priceRangeSlider.MaxValue = TRConstant.MaxValidBudget;

			if (ViewModelInstance.MinBudget < TRConstant.MinValidBudget || ViewModelInstance.MinBudget > TRConstant.MaxValidBudget) {
				priceRangeSlider.LeftValue = TRConstant.MinValidBudget;
			} else {
				priceRangeSlider.LeftValue = (nfloat)ViewModelInstance.MinBudget;
			}

			if (ViewModelInstance.MaxBudget > TRConstant.MaxValidBudget || ViewModelInstance.MaxBudget < TRConstant.MinValidBudget) {
				priceRangeSlider.RightValue = TRConstant.MaxValidBudget;
			} else {
				priceRangeSlider.RightValue = (nfloat)ViewModelInstance.MaxBudget;
			}

			priceRangeSlider.LeftValueChanged += (nfloat value) => {
				ViewModelInstance.MinBudget = priceRangeSlider.LeftValue;
			};

			priceRangeSlider.RightValueChanged += (nfloat value) => {
				ViewModelInstance.MaxBudget = priceRangeSlider.RightValue;
			};

			this.view_rangeSlider.AddSubview (priceRangeSlider);
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);

			this.NavigationController.SetNavigationBarHidden (false, true);
			this.NavigationController.SetToolbarHidden (true, true);
		}

		public override void ViewDidLayoutSubviews ()
		{
			base.ViewDidLayoutSubviews ();
			if (priceRangeSlider != null) {
				priceRangeSlider.Frame = new CGRect (0, 0, this.view_rangeSlider.Frame.Width, this.view_rangeSlider.Frame.Height);
			}
		}
	}
}
