// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ThisRoofN.iOS
{
	public partial class HomeStructureModalView : UIViewController
	{
		public HomeStructureModalView (IntPtr handle) : base (handle)
		{
		}
	}
}
