// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using MvvmCross.Binding.iOS.Views;
using CoreGraphics;
using MvvmCross.Binding.BindingContext;

namespace ThisRoofN.iOS
{
	public partial class PropertyTypeModalView : BaseModalView
	{
		public PropertyTypeModalView (IntPtr handle) : base (handle)
		{
		}

		public PropertyTypeModalViewModel ViewModelInstance {
			get {
				return (PropertyTypeModalViewModel)base.ViewModel;
			}
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			// Bind Item Tableview source
			var source = new PropertyTypesTableViewSource (this, tbl_propertyTypes);
			tbl_propertyTypes.Source = source;
			tbl_propertyTypes.RowHeight = UITableView.AutomaticDimension;
			tbl_propertyTypes.TableFooterView = new UITableView (CGRect.Empty);
			tbl_propertyTypes.SeparatorStyle = UITableViewCellSeparatorStyle.None;
			tbl_propertyTypes.ReloadData ();

			var bindingSet = this.CreateBindingSet<PropertyTypeModalView, PropertyTypeModalViewModel> ();
			bindingSet.Bind (btn_back).To (vm => vm.ModalCloseCommand);
			bindingSet.Bind (source).To (vm => vm.Items);
			bindingSet.Apply ();


			this.view_side.AddGestureRecognizer (new UITapGestureRecognizer (() => {
				ViewModelInstance.ModalCloseCommand.Execute(null);
			}));
		}

		public class PropertyTypesTableViewSource : MvxTableViewSource
		{
			PropertyTypeModalView masterView;
			public PropertyTypesTableViewSource (PropertyTypeModalView _masterView, UITableView tv) : base (tv)
			{
				this.masterView = _masterView;
			}

			public override nfloat GetHeightForRow (UITableView tableView, NSIndexPath indexPath)
			{
				return 60.0f;
			}

			protected override UITableViewCell GetOrCreateCellFor (UITableView tableView, NSIndexPath indexPath, object item)
			{
				PropertyTypeItemCell cell = (PropertyTypeItemCell)tableView.DequeueReusableCell (PropertyTypeItemCell.Identifier);
				return cell;
			}

			public override void RowSelected (UITableView tableView, NSIndexPath indexPath)
			{
				tableView.DeselectRow (indexPath, true);
				masterView.ViewModelInstance.Items [indexPath.Row].Selected = !masterView.ViewModelInstance.Items [indexPath.Row].Selected;
			}
		}
	}
}
