// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using CoreGraphics;

namespace ThisRoofN.iOS
{
	public partial class SearchAreaLocationHeaderView : UICollectionReusableView
	{
		public SearchAreaLocationHeaderView (IntPtr handle) : base (handle)
		{
		}

		public void InitView()
		{
			SelectAllButton.Layer.BorderWidth = 1.0f;
			SelectAllButton.Layer.BorderColor = UIColor.LightGray.CGColor;
			SelectAllButton.Layer.CornerRadius = 3.0f;

			ClearAllButton.Layer.BorderWidth = 1.0f;
			ClearAllButton.Layer.BorderColor = UIColor.LightGray.CGColor;
			ClearAllButton.Layer.CornerRadius = 3.0f;

			switch_city.Transform = CGAffineTransform.MakeScale(0.75f, 0.75f);
			switch_metro.Transform = CGAffineTransform.MakeScale(0.75f, 0.75f);
			switch_rural.Transform = CGAffineTransform.MakeScale(0.75f, 0.75f);
			switch_suburb.Transform = CGAffineTransform.MakeScale(0.75f, 0.75f);

			switch_rural.On = false;
		}

		public UIButton SelectAllButton
		{
			get {
				return btn_selectAll;
			}
		}

		public UIButton ClearAllButton
		{
			get {
				return btn_clearAll;
			}
		}
	}
}
