// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using MvvmCross.Binding.iOS.Views;
using MvvmCross.Binding.BindingContext;
using ThisRoofN.Models.App;
using ThisRoofN.Models.Service;

namespace ThisRoofN.iOS
{
	public partial class SRDetailImageCell : MvxTableViewCell
	{
		public static string Identifier = "SRDetailImageCell";

		public SRDetailImageCell (IntPtr handle) : base (handle)
		{
//			this.DelayBind (() => {
//				var set = this.CreateBindingSet<SRDetailImageCell, CottagePhoto>();
//				set.Bind(img_detailItem).For(i => i.ImageUrl).To(vm => vm.MediaURL);
//				set.Apply();
//			});
		}

		public MvxImageView IVItem {
			get {
				return img_detailItem;
			}
		}
	}
}
