// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ThisRoofN.iOS
{
	public partial class SRDetailValueCell : UITableViewCell
	{
		public static string Identifier = "SRDetailValueCell";

		private SearchResultDetailView masterView;
		private nfloat cellHeight;

		public SRDetailValueCell (IntPtr handle) : base (handle)
		{
		}

		public nfloat CellHeight 
		{
			get
			{
				return cellHeight;
			}
		}

		public void BindData(SearchResultDetailView _masterView)
		{
			this.masterView = _masterView;

			_masterView.BindingSet.Bind (lbl_street).To (vm => vm.ItemDetail.FormattedAddress);
			_masterView.BindingSet.Bind (lbl_address).To (vm => vm.ItemDetail.FormattedCityStateZip);
			_masterView.BindingSet.Bind (lbl_price).To (vm => vm.ItemDetail.Value);
			_masterView.BindingSet.Bind (lbl_sqft).To (vm => vm.ItemDetail.SquareFootageStructure);
			_masterView.BindingSet.Bind (lbl_lotSqft).To (vm => vm.ItemDetail.LotSquareFootage);
			_masterView.BindingSet.Bind (lbl_bd).To (vm => vm.ItemDetail.Bedrooms);
			_masterView.BindingSet.Bind (lbl_ba).To (vm => vm.ItemDetail.BathsFull);

			InitUI ();
		}

		private void InitUI()
		{
			cellHeight = view_contact.Frame.Bottom;
		}
	}
}
