// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ThisRoofN.iOS
{
	public partial class SRDetailTitleCell : UITableViewCell
	{
		public static string Identifier = "SRDetailTitleCell";

		private SearchResultDetailView masterView;
		private nfloat cellHeight;

		public SRDetailTitleCell (IntPtr handle) : base (handle)
		{
		}

		public nfloat CellHeight 
		{
			get
			{
				return cellHeight;
			}
		}

		public void BindData(SearchResultDetailView _masterView)
		{
			this.masterView = _masterView;

			img_major.DefaultImagePath = NSBundle.MainBundle.PathForResource ("img_placeholder", "png");
			masterView.BindingSet.Bind (img_major).For (i => i.ImageUrl).To (vm => vm.ItemDetail.PrimaryPhotoLink);
			masterView.BindingSet.Bind (lbl_budget).To (vm => vm.ItemDetail.FormattedPrice);
			masterView.BindingSet.Bind (lbl_address).To (vm => vm.ItemDetail.FormattedCityStateZip);
			masterView.BindingSet.Bind (lbl_bedBath).To (vm => vm.ItemDetail.FormattedBedBath);
			masterView.BindingSet.Bind (lbl_sqft).To (vm => vm.ItemDetail.FormattedSquareFootageStructure);
			masterView.BindingSet.Bind (lbl_acre).To (vm => vm.ItemDetail.FormattedAcreValue).WithConversion(new StringFormatConverter(), "LOT: {0} Acres");
			masterView.BindingSet.Bind (lbl_acre).For (i => i.Hidden).To (vm => vm.ItemDetail.IsFormattedAcreValueHide);

			InitUI ();
		}

		private void InitUI()
		{
			cellHeight = (UIScreen.MainScreen.Bounds.Height - 60) / 2;
		}
	}
}
