// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using MvvmCross.Binding.iOS.Views;
using MvvmCross.Binding.BindingContext;

namespace ThisRoofN.iOS
{
	public partial class SRTileImageCell : MvxCollectionViewCell
	{
		public static string Identifier = "SRDetailValueCell";

		public SRTileImageCell (IntPtr handle) : base (handle)
		{
			this.DelayBind (() => {
				var set = this.CreateBindingSet<SRTileImageCell, TileItemModel>();
				set.Bind(img_item).For(i => i.ImageUrl).To(vm => vm.ImageUrl);
				set.Apply();
			});
		}
	}
}
