// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using MvvmCross.Binding.iOS.Views;
using MvvmCross.Binding.BindingContext;
using ThisRoofN.Models.App;
using CoreAnimation;
using CoreGraphics;

namespace ThisRoofN.iOS
{
	public partial class SRTileImageCell : MvxCollectionViewCell
	{
		public static string Identifier = "SRDetailValueCell";

		public SRTileImageCell (IntPtr handle) : base (handle)
		{
			this.DelayBind (() => {
				var set = this.CreateBindingSet<SRTileImageCell, TRCottageSimple>();

				set.Bind(img_item).For(i => i.ImageUrl).To(vm => vm.PrimaryPhotoLink);
				set.Bind(lbl_title).To(vm => vm.Title);
				set.Bind(lbl_itemPrice).To(vm => vm.FormattedPrice);
				set.Apply();
			});
		}

		public UIView ViewTitleBack
		{
			get {
				return view_titleBack;
			}
		}

		public MvxImageView IVItem
		{
			get {
				return img_item;
			}
		}

		public override void Draw (CoreGraphics.CGRect rect)
		{
			base.Draw (rect);

			if (view_titleBack != null) {
				view_titleBack.Layer.Sublayers[0].Frame = view_titleBack.Bounds;
			}
		}

		public override CoreGraphics.CGRect Frame {
			get {
				return base.Frame;
			}
			set {
				base.Frame = value;
			}
		}
	}
}
